In [1]:
import pandas as pd
import numpy as np
from libs import ModelManager as mm
from config import basic_conf as conf
import logging

from importlib import reload

In [2]:
conf.init_logger(logging.INFO, logfile=None)
mgr = mm.ModelManager(mode='notebook')

[2018-10-27 13:13:29] [INFO] Initializing Model Manager, version 0.4.0 ...
[2018-10-27 13:13:29] [INFO] 
=== Models Available ===
BagOfWords
NLIRNN
[2018-10-27 13:13:29] [INFO] 
=== Loaders Available ===
IMDB
SNLI
[2018-10-27 13:13:29] [INFO] 
*********** Model Manager Details ***********
-- self.hparams.num_epochs = 1
-- self.hparams.lr = 0.01
-- self.hparams.voc_size = 100000
-- self.hparams.train_loop_check_freq = 10
-- self.hparams.dropout = 0.5
-- self.hparams.batch_size = 4
-- self.hparams.fc_hidden_size = 100
-- self.hparams.rnn_hidden_size = 50
-- self.hparams.rnn_num_layers = 2
-- self.hparams.check_early_stop = True
-- self.hparams.es_look_back = 10
-- self.hparams.es_req_prog = 0.01
-- self.hparams.optim_enc = <class 'torch.optim.adam.Adam'>
-- self.hparams.optim_dec = <class 'torch.optim.adam.Adam'>
-- self.hparams.scheduler = <class 'torch.optim.lr_scheduler.ExponentialLR'>
-- self.hparams.scheduler_gamma = 0.95
-- self.hparams.criterion = <class 'torch.nn.modules.loss.Cro

In [3]:
mgr.load_data(mm.loaderRegister.SNLI, train_size=1)

[2018-10-27 13:13:29] [INFO] Loading data using SNLI ...
[2018-10-27 13:13:29] [INFO] loading raw training data set ...
[2018-10-27 13:13:29] [INFO] loading raw training data set ...
[2018-10-27 13:13:29] [INFO] loading pre-trained word vectors, building vocab ...
[2018-10-27 13:13:42] [INFO] converting training set to index ...
[2018-10-27 13:13:42] [INFO] converting val set to index ...
[2018-10-27 13:13:42] [INFO] piping data into pytorch DataLoaders ...


In [4]:
mgr.new_model(mm.modelRegister.NLIRNN)

[2018-10-27 13:13:42] [INFO] 
*********** Model: scratch Details ***********
-- self.label = scratch
-- self.hparams.num_epochs = 1
-- self.hparams.lr = 0.01
-- self.hparams.voc_size = 100000
-- self.hparams.train_loop_check_freq = 10
-- self.hparams.dropout = 0.5
-- self.hparams.batch_size = 4
-- self.hparams.fc_hidden_size = 100
-- self.hparams.rnn_hidden_size = 50
-- self.hparams.rnn_num_layers = 2
-- self.hparams.check_early_stop = True
-- self.hparams.es_look_back = 10
-- self.hparams.es_req_prog = 0.01
-- self.hparams.optim_enc = <class 'torch.optim.adam.Adam'>
-- self.hparams.optim_dec = <class 'torch.optim.adam.Adam'>
-- self.hparams.scheduler = <class 'torch.optim.lr_scheduler.ExponentialLR'>
-- self.hparams.scheduler_gamma = 0.95
-- self.hparams.criterion = <class 'torch.nn.modules.loss.CrossEntropyLoss'>
-- self.lparams.act_vocab_size = 100002
-- self.lparams.pre_trained_vecs = [[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.01750315  0.25247643

In [5]:
model = mgr.model.model

In [6]:
model

RNN(
  (embed): Embedding(100002, 300)
  (rnn): GRU(300, 50, num_layers=2, batch_first=True, dropout=0.5, bidirectional=True)
  (fc): Sequential(
    (0): Linear(in_features=100, out_features=100, bias=True)
    (1): ReLU()
    (2): Linear(in_features=100, out_features=3, bias=True)
  )
)

In [10]:
l_data = mgr.dataloader.data['train']

In [13]:
di = l_data[0]

In [14]:
di.token_idx_tuple

([9, 802, 1830, 8, 9, 6265, 7167, 4388, 17, 9, 12229, 5335, 9, 563, 6, 358, 4],
 [9, 802, 1830, 2255, 3, 13985, 94, 3, 358, 4])

In [7]:
l = mgr.dataloader.loaders['train']

In [15]:
for sent1_batch, sent2_batch, len1_batch, len2_batch, label_batch in l:
    print(len1_batch)
    print(sent1_batch)
    break

tensor([17])
tensor([[    9,   802,  1830,     8,     9,  6265,  7167,  4388,    17,     9,
         12229,  5335,     9,   563,     6,   358,     4]])


In [16]:
import torch

In [20]:
# create a tensor for dim (4, 4, 10)
tsr = torch.FloatTensor(torch.randn(2, 4, 5))
tsr

tensor([[[ 0.0762, -0.4489,  0.5261, -1.0677,  0.8781],
         [ 0.7237,  2.6297, -1.5563,  1.1433, -0.4791],
         [-1.0312,  0.3659,  0.0245, -0.7548, -0.1548],
         [ 0.2657,  0.2099,  0.0686,  0.5378,  1.0993]],

        [[-1.0358,  0.4978, -1.2232, -0.4774,  0.3099],
         [-2.2463,  0.0905,  0.3335,  1.2132,  1.1002],
         [ 0.3427, -0.5845, -0.5027,  1.1077, -0.4983],
         [ 0.5663,  0.6057, -0.1243,  0.3221,  0.1894]]])

In [25]:
tsr.squeeze(0)

tensor([[[ 0.0762, -0.4489,  0.5261, -1.0677,  0.8781],
         [ 0.7237,  2.6297, -1.5563,  1.1433, -0.4791],
         [-1.0312,  0.3659,  0.0245, -0.7548, -0.1548],
         [ 0.2657,  0.2099,  0.0686,  0.5378,  1.0993]],

        [[-1.0358,  0.4978, -1.2232, -0.4774,  0.3099],
         [-2.2463,  0.0905,  0.3335,  1.2132,  1.1002],
         [ 0.3427, -0.5845, -0.5027,  1.1077, -0.4983],
         [ 0.5663,  0.6057, -0.1243,  0.3221,  0.1894]]])

In [34]:
tsr_tuple = tuple(tsr[x] for x in range(tsr.shape[0]))

In [41]:
torch.cat(tsr_tuple, 1)

tensor([[ 0.0762, -0.4489,  0.5261, -1.0677,  0.8781, -1.0358,  0.4978, -1.2232,
         -0.4774,  0.3099],
        [ 0.7237,  2.6297, -1.5563,  1.1433, -0.4791, -2.2463,  0.0905,  0.3335,
          1.2132,  1.1002],
        [-1.0312,  0.3659,  0.0245, -0.7548, -0.1548,  0.3427, -0.5845, -0.5027,
          1.1077, -0.4983],
        [ 0.2657,  0.2099,  0.0686,  0.5378,  1.0993,  0.5663,  0.6057, -0.1243,
          0.3221,  0.1894]])

In [43]:
import torch.nn as nn

In [44]:
loss = nn.CrossEntropyLoss()
_input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(_input, target)
output.backward()

In [45]:
_input.shape

torch.Size([3, 5])

In [46]:
target.shape

torch.Size([3])

In [ ]:
hs = [4, 4, 50]